### PR TITLE
Simulator on x86. Fixing the bundling

### PR DESCRIPTION
**Pull request by KaruroChori**
Not really to be merged, more to show some fixes and stuff I changed to make it usable on my system.
At the moment both demos are quite broken for me (they also were in the original repo):
- The calculator works somewhat, except that it does not calculate.
- The demo with the widgets is just a blank screen with the cursor being drawn.

I changed the bundler script to generate both the demo js and tests. And I added the target to use the simulator on x86 since ti was missing.

### CODE REVIEW

**Comment by KaruroChori** [comment]
The issue with rendering is due to the newer versions of react which changed the interface of the reconciler.
Using the old packages:
```
    "react": "^16.13.1",
    "react-proxy": "^2.0.8",
    "react-reconciler": "^0.25.1",
    "react-router": "^6.3.0",
```
will lead to both demos working.

**Comment by jspngh** [comment]
Thanks! I've integrated your improvements and I think I'm ready for creating a PR to the upstream project, so I'll do that shortly.

**Comment by jspngh** [comment]
> I think I'm ready for creating a PR to the upstream project, so I'll do that shortly.

Hmm, after testing again, I see that when closing the simulator the shutdown isn't clean:
```
free(): invalid pointer
'./build/lvgljs run test/animate…' terminated by signal SIGABRT (Abort)
```
I'm going to try to fix that before creating a PR.

**Comment by KaruroChori** [comment]
Yes, I also noticed that for every run I tested, but I forgot to report it.

**Comment by jspngh** [comment]
Okay, so I finally had time to look at it.
It's a really weird bug. From what I can see it's happening in the shutdown of libuv.
`uv__process_title_cleanup` is called, which calls `uv__free(args_mem)`.
This `args_mem` is allocated at startup, so it makes sense to clean it up.

However, the `uv__allocator` has been swapped at that point for some reason.
When mimalloc is enabled (which is the default), txiki will tell uv to use the mimalloc functions,
but in the shutdown it's no longer using them, but rather the "standard/glibc free", which causes the "invalid pointer".

This happens from the moment you initialize SDL (used for the simulator), so it has to have something to do with it.
If you don't initialize SDL, it can shut down cleanly.
Also, I don't remember if this behaviour also happens on macos, or only on Linux.

As a hacky workaround, I just disable mimalloc when building the simulator, but it warrants some extra investigation.
I'll use this information to create a bug report if my PR is accepting in lv_binding_js.

**Comment by jspngh** [comment]
@KaruroChori: PR is open https://github.com/lvgl/lv_binding_js/pull/32

**Comment by KaruroChori** [comment]
What allocator is lvgl internally using? Is there any field to configure it in the `.h` config file? That might be a possible explanation, ~but I cannot check right now.~

https://github.com/jspngh/lv_binding_js/blob/2624892dbb9dfcc9f21f2a75581fa0fe9507cb7e/src/deps/lv_conf.h#L49

**Pull request closed without merging**
